CREATE TABLE by_age (
	entity VARCHAR,
	code VARCHAR,
	year int,
	"All Ages" FLOAT,
	"Under 5" FLOAT,
	"5 to 14" FLOAT,
	"15 to 49" FLOAT,
	"50 to 69" FLOAT,
	"Over 70" FLOAT
);

CREATE TABLE by_type (
	"entity" VARCHAR,
	"code" VARCHAR,
	"year" int,
	"Liver" FLOAT,
	"Kidney" FLOAT,
	"Larynx" FLOAT,
	"Breast" FLOAT,
	"Thyroid" FLOAT,
	"Bladder" FLOAT,
	"Uterine" FLOAT,
	"Ovarian" FLOAT,
	"Stomach" FLOAT,
	"Prostate" FLOAT,
	"Cervical" FLOAT,
	"Testicular" FLOAT,
	"Pancreatic" FLOAT,
	"Esophageal" FLOAT,
	"Nasopharynx" FLOAT,
	"Colon and Rectum" FLOAT,
	"Nonmelanoma Skin" FLOAT,
	"Lip and Oral Cavity" FLOAT,
	"Brain and Nervous System" FLOAT,
	"Tracheal, Bronchus, and Lung" FLOAT,
	"Gallbladder and Biliary Tract" FLOAT	
);

CREATE TABLE death_by_type (
"entity" VARCHAR,
	"code" VARCHAR,
	"year" INT,
	"Liver" INT,
	"Kidney" INT,
	"Larynx" INT,
	"Breast" INT,
	"Thyroid" INT,
	"Bladder" INT,
	"Uterine" INT,
	"Ovarian" INT,
	"Stomach" INT,
	"Prostate" INT,
	"Cervical" INT,
	"Testicular" INT,
	"Pancreatic" INT,
	"Esophageal" INT,
	"Nasopharynx" INT,
	"Colon and Rectum" INT,
	"Nonmelanoma Skin" INT,
	"Lip and Oral Cavity" INT,
	"Brain and Nervous System" INT,
	"Tracheal, Bronchus, and Lung" INT,
	"Gallbladder and Biliary Tract" INT
);