CREATE TABLE by_age (
	entity VARCHAR,
	code VARCHAR,
	year int,
	"all_ages" FLOAT,
	"under_five" FLOAT,
	"five_to_fourteen" FLOAT,
	"fifteen_to_fortynine" FLOAT,
	"fifty_to_sixtynine" FLOAT,
	"seventy_plus" FLOAT
);

CREATE TABLE by_type (
	"entity" VARCHAR,
	"code" VARCHAR,
	"year" int,
	"liver" FLOAT,
	"kidney" FLOAT,
	"larynx" FLOAT,
	"breast" FLOAT,
	"thyroid" FLOAT,
	"bladder" FLOAT,
	"uterine" FLOAT,
	"ovarian" FLOAT,
	"stomach" FLOAT,
	"prostate" FLOAT,
	"cervical" FLOAT,
	"testicular" FLOAT,
	"pancreatic" FLOAT,
	"esophageal" FLOAT,
	"nasopharynx" FLOAT,
	"colon_and_rectum" FLOAT,
	"nonmelanoma_skin" FLOAT,
	"lip_and_oral_cavity" FLOAT,
	"brain_and_nervous_system" FLOAT,
	"tracheal_bronchus_lung" FLOAT,
	"gallbladder_and_biliary_tract" FLOAT	
);

CREATE TABLE death_by_type (
"entity" VARCHAR,
	"code" VARCHAR,
	"year" INT,
	"liver" INT,
	"kidney" INT,
	"larynx" INT,
	"breast" INT,
	"thyroid" INT,
	"bladder" INT,
	"uterine" INT,
	"ovarian" INT,
	"stomach" INT,
	"prostate" INT,
	"cervical" INT,
	"testicular" INT,
	"pancreatic" INT,
	"esophageal" INT,
	"nasopharynx" INT,
	"colon_and_rectum" INT,
	"nonmelanoma_skin" INT,
	"lip_and_oral_cavity" INT,
	"brain_and_nervous_system" INT,
	"tracheal_bronchus_lung" INT,
	"gallbladder_and_biliary_tract" INT
);